action_stats:
  min: [-2.5, -4, -3.14] # [min_dx, min_dy, min_dyaw]
  max: [5, 4, 3.14] # [max_dx, max_dy, max_dyaw]

recon:
  metric_waypoint_spacing: 0.25 # average spacing between waypoints (meters)

scand:
  metric_waypoint_spacing: 0.38

tartan_drive:
  metric_waypoint_spacing: 0.72

go_stanford:
  metric_waypoint_spacing: 0.12

sacson:
  metric_waypoint_spacing: 0.255
