# L40S GPU training configuration - Hybrid memory model
# Training without buffer, memory mechanism enabled during inference
run_name: hybrid_l40s_inference_memory

# output
results_dir: logs_L40S_hybrid_latents

# training switches
train: True
eval_decode: false

# hardware & precision
#accelerator: gpu         
#gpus: 2                  
#strategy: ddp            
#precision: 16            

# batch & data loading
batch_size: 16           # Updated to match L40S latent config
num_workers: 16          # Updated to match L40S latent config

# hybrid model configuration
model: CDiT-L/2          
use_hybrid_model: true
memory_enabled: true     # Enable during inference
memory_buffer_size: 50
memory_layers: [0, 6, 12, 18]  # Activate memory at these layers

# model & optimization
lr: 2e-5                 # Updated to match L40S latent config
normalize: True
grad_clip_val: 10.0      # Updated to match L40S latent config
image_size: 224          # Updated to match L40S latent config
context_size: 4          # Updated to match L40S latent config
len_traj_pred: 32        # Updated to match L40S latent config

# training schedule
warmup_steps: 1000

lr_scheduler:
  name: linear
  total_steps: 100000

# distance classification
distance:
  min_dist_cat: -64      # Updated to match L40S latent config
  max_dist_cat: 64       # Updated to match L40S latent config

# dataset configuration - updated to use latent folders
datasets:
  recon:
    latent_folder: latents/recon
    train: data_splits/recon/train
    test: data_splits/recon/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  scand:
    latent_folder: latents/scand
    train: data_splits/scand/train
    test: data_splits/scand/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  tartan_drive:
    latent_folder: latents/tartan_drive
    train: data_splits/tartan_drive/train
    test: data_splits/tartan_drive/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  sacson:
    latent_folder: latents/sacson
    train: data_splits/sacson/train
    test: data_splits/sacson/test
    traj_names: traj_names.txt
    goals_per_obs: 2

# L40S optimization settings
pin_memory: true
persistent_workers: true

# memory weight configuration (used only during inference)
spatial_weight: 0.8  # Spatial similarity weight
action_weight: 0.2   # Action similarity weight

# behavior classification thresholds
behavior_thresholds:
  straight_threshold: 0.1    # Below 6 degrees considered straight
  minor_adjust_threshold: 0.3  # Below 17 degrees considered minor adjustment
  turn_threshold: 1.0        # Below 57 degrees considered turn
