run_name: hybrid_nwm_cdit_l_latents_L40S

# training setup
results_dir: logs_hybrid_latents
train: True
batch_size: 4              # to tune regarding the performance
num_workers: 4
model: CDiT-L/2
lr: 6e-5
normalize: True
grad_clip_val: 10.0
context_size: 3
eval_decode: false

# Hybrid model specific configurations
use_hybrid_model: true     # Enable hybrid CDiT with memory
memory_enabled: true       # Enable memory mechanisms
memory_buffer_size: 50     # Size of memory buffer
memory_layers: [16, 18, 20, 22]  # Which layers to add memory (later layers)

# Memory activation parameters
memory_activation_threshold: 0.3   # Threshold for memory activation
spatial_similarity_threshold: 0.7  # Threshold for spatial similarity matching

distance:
  min_dist_cat: -64
  max_dist_cat: 64

len_traj_pred: 32
image_size: 160            # requis uniquement pour compatibilité

datasets:
  scand:
    data_folder: latents/scand   # <- ici on pointe vers les latents
    train: "AAAAA"
    test: ""         
    goals_per_obs: 1
