# L40S GPU training configuration - Hybrid CDiT with WorldMem integration
# Training hybrid model with memory mechanisms for navigation world modeling
run_name: hybrid_nwm_cdit_l_latents_L40S

# output
results_dir: logs/nwm_cdit_xl

# training switches
train: True
eval_decode: false

# hardware & precision
#accelerator: gpu         
#gpus: 2                  
#strategy: ddp            
#precision: 16            

# batch & data loading
batch_size: 16           # Updated to match L40S latent config
num_workers: 16          # Updated to match L40S latent config

# hybrid model configuration - WorldMem integration
model: CDiT-L/2          
use_hybrid_model: true
memory_enabled: true     # Enable memory during training and inference
memory_buffer_size: 100  # Increased buffer size for better memory capacity
memory_layers: [0, 6, 12, 18, 24]  # Extended memory layers for L/2 model
memory_update_frequency: 50  # Update memory every N steps during training
adaptive_memory_weights: true  # Enable adaptive memory weight adjustment

# model & optimization
lr: 2e-5                 # Updated to match L40S latent config
normalize: True
grad_clip_val: 10.0      # Updated to match L40S latent config
image_size: 224          # Updated to match L40S latent config
context_size: 4          # Updated to match L40S latent config
len_traj_pred: 32        # Updated to match L40S latent config

# training schedule
warmup_steps: 1000

lr_scheduler:
  name: linear
  total_steps: 100000

# distance classification
distance:
  min_dist_cat: -64      # Updated to match L40S latent config
  max_dist_cat: 64       # Updated to match L40S latent config

# dataset configuration - updated to use latent folders
datasets:
  recon:
    latent_folder: latents/recon
    train: data_splits/recon/train
    test: data_splits/recon/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  scand:
    latent_folder: latents/scand
    train: data_splits/scand/train
    test: data_splits/scand/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  tartan_drive:
    latent_folder: latents/tartan_drive
    train: data_splits/tartan_drive/train
    test: data_splits/tartan_drive/test
    traj_names: traj_names.txt
    goals_per_obs: 2
  sacson:
    latent_folder: latents/sacson
    train: data_splits/sacson/train
    test: data_splits/sacson/test
    traj_names: traj_names.txt
    goals_per_obs: 2

# L40S optimization settings
pin_memory: true
persistent_workers: true

# Advanced memory weight configuration with adaptive scoring
retrieval_weights:
  spatial_weight: 0.45        # Base spatial similarity weight
  action_weight: 0.35         # Base action similarity weight  
  memory_weight: 0.15         # Memory usage pattern weight
  usage_weight: 0.05          # Access frequency weight

# Zero-parameter adaptive scoring system
adaptive_scoring:
  enabled: true
  complexity_threshold: 0.4   # Use adaptive weights when complexity > threshold
  linear_speed_thresholds:
    slow: 0.1                 # Below this: increase spatial weight
    fast: 0.4                 # Above this: increase action weight
  turn_thresholds:
    minor: 0.15               # Below 8.5 degrees
    major: 0.3                # Above 17 degrees

# behavior classification thresholds
behavior_thresholds:
  straight_threshold: 0.1    # Below 6 degrees considered straight
  minor_adjust_threshold: 0.3  # Below 17 degrees considered minor adjustment
  turn_threshold: 1.0        # Below 57 degrees considered turn
