run_name: nwm_cdit_b_latents

# training setup
results_dir: logs_latents
train: True
batch_size: 12 
num_workers: 8
model: CDiT-B/2
lr: 6e-5
normalize: True
grad_clip_val: 10.0
context_size: 3
eval_decode: false

# scheduler / warm-up
warmup_steps: 1000

lr_scheduler:
  name: linear
  total_steps: 100000

distance:
  min_dist_cat: -64
  max_dist_cat: 64

len_traj_pred: 32
image_size: 224 

datasets:
  recon:
    latent_folder: latents/recon
    train: data_splits/recon/train
    test: data_splits/recon/test
    traj_names: traj_names.txt
    goals_per_obs: 1
  scand:
    latent_folder: latents/scand
    train: data_splits/scand/train
    test: data_splits/scand/test
    traj_names: traj_names.txt
    goals_per_obs: 1
  tartan_drive:
    latent_folder: latents/tartan_drive
    train: data_splits/tartan_drive/train
    test: data_splits/tartan_drive/test
    traj_names: traj_names.txt
    goals_per_obs: 1
  sacson:
    latent_folder: latents/sacson
    train: data_splits/sacson/train
    test: data_splits/sacson/test
    traj_names: traj_names.txt
    goals_per_obs: 1
