run_name: nwm_cdit_l_latents_4070ti

# training setup
results_dir: logs_4070ti_latents
train: True
batch_size: 4              # to tune regarding the performance
num_workers: 4
model: CDiT-L/2
lr: 6e-5
normalize: True
grad_clip_val: 10.0
context_size: 3
eval_decode: false

distance:
  min_dist_cat: -64
  max_dist_cat: 64

len_traj_pred: 32
image_size: 160            # requis uniquement pour compatibilité

datasets:
  scand:
    data_folder: latents/scand   # <- ici on pointe vers les latents
    train: "AAAAA"
    test: ""         
    goals_per_obs: 1
